#!/usr/bin/perl

use strict;
use warnings;
use CGI 'header';
use Text::MultiMarkdown 'markdown';

main();

#---------------------------------------------------

sub getfile {
  # Return the contents of a given file
  my $file = shift;
  return "Error fetching file $file" unless -e $file;
  open(IN, $file) or return;
  my $out = join('', <IN>);
  close IN;
  return $out;
}

sub update {
   chdir '/var/repo';
   print header(), `git pull 2>&1`;
   return 1;
}

sub main {
  my $file = $ENV{PATH_TRANSLATED};
  return update() if $ENV{QUERY_STRING} eq 'update';
  my $content = markdown( getfile $file );
  my ($title) = $content =~ /<h1[^>]*>(.+)<\/h1>/i;
  $title ||= '';
  my $tmpl = getfile('tmpl.html');
  $tmpl =~ s/CONTENT/$content/s;
  $tmpl =~ s/TITLE/$title/gs;
  $tmpl =~ s/BASEURL/\/parsec-test/gs;
  $tmpl =~ s/DATE//s;

  print header(-charset => 'UTF-8');
  print $tmpl;
}

