
name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  web_update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update hpcg website
        run: wget -q --content-on-error -O - http://hpcg-benchmark.org/tmpl?update

      - name: Update hpl-mxp.org website
        run: wget -q --content-on-error -O - http://hpl-mxp.org/tmpl?update

      - name: Update hpg-mxp.org website
        run: wget -q --content-on-error -O - http://hpg-mxp.org/tmpl?update

