
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  web_update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update hpcg website
        run: wget -O - -q http://hpcg-benchmark.org/tmpl?update

      - name: Update hpl-mxp.org website
        run: wget -O - -q http://hpl-mxp.org/tmpl?update

      - name: Update hpg-mxp.org website
        run: wget -O - -q http://hpg-mxp.org/tmpl?update

