
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  web_update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Trigger a website update
        run: curl http://test.icl.utk.edu/parsec/?update
